title: Jan Corazza's blog
author: Jan Corazza
description: math, AI, functional programming, philosophy, ...
show_excerpts: true

theme: minima
minima:
  social_links:
    twitter: jancorazza
    github: corazza
  skin: auto

twitter_username: jancorazza
github_username:  corazza

plugins:
  - jekyll-feed
