title: flowing → systems
author: Jan Corazza
description: personal blog
show_excerpts: true

theme: minima
minima:
  social_links:
    twitter: jancorazza
    github: corazza

twitter_username: jancorazza
github_username:  corazza
