title: flowing → systems
author: Jan Corazza
description: math, AI, functional programming, philosophy, ...
show_excerpts: true

theme: minima
minima:
  social_links:
    twitter: jancorazza
    github: corazza

twitter_username: jancorazza
github_username:  corazza


plugins:
  - jekyll-feed
